version: '3.8'

volumes:
    data: {}

services:
  jenkins:
    container_name: jenkins
    image: 'jenkins/jenkins:2.249.2-lts'
    networks:
      - proxy
    ports:
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${docker_bin}:/bin/docker
      - ${docker_compose_bin}:/bin/docker-compose

networks:
  proxy:
    external:
      name: traefik_proxy
